# Step 1: Build stage
FROM eclipse-temurin:17-jdk-alpine AS build

WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Download dependencies first (leverages Docker layer caching)
RUN ./mvnw dependency:go-offline -B

# Copy source and build the application
COPY src src
RUN ./mvnw clean package -DskipTests

# Step 2: Run stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Expose the port Spring Boot runs on
EXPOSE 8080
#for debugging ports
#EXPOSE 8080 5005


# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
#for debugging purpose
#ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]



