spring:
  application:
    name: employee-service
    include-stack-trace: false
    support-email: support@example.com
    docs-url: https://docs.example.com
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3307}/${EMPLOYEE_DB_NAME:employee}
    url: jdbc:mysql://localhost:3307/employee
    username: ${MYSQL_DB_USERNAME:myRoot}
    password: ${MYSQL_DB_PASSWORD:generic}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.microservices34: DEBUG
    org.springframework.web: INFO